# Numpy
- Numpy is a numerical computing library for python.
- Numpy support multi dimensional arrays and matrices
- It has a lot of in-built mathematical functions

In [1]:
l=[[1,2],[3,4]]

In [2]:
!pip install numpy

In [3]:
import numpy as np

# Why Numpy ?
- performs fast operations (because of Vectorization)
- numpy arrays can be treated as vectors and matrices from linear algebra


In [4]:
lst = [1,2,9,4,5,6,7,8,9,10,11]

In [5]:
[x**2 for x in lst]

[1, 4, 81, 16, 25, 36, 49, 64, 81, 100, 121]

In [6]:
%timeit [x**2 for x in lst]

1.47 µs ± 27.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
arr=np.array(lst)

In [8]:
arr

array([ 1,  2,  9,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
arr=arr**2

In [10]:
%timeit arr**2

960 ns ± 15 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Numpy Basics
array : Fundamental element in numpy is homogenous array. Numpy Arrays can be 1D, 2D, 3D . . . nD

- Different ways to create np array
    1. np.array()
    2. np.arange()

In [11]:
arr.ndim

1

In [12]:
arr1=np.array([[2,4,1],[3,9,5]])

In [13]:
arr1

array([[2, 4, 1],
       [3, 9, 5]])

In [14]:
arr1.ndim

2

In [15]:
arr1.shape

(2, 3)

In [16]:
arr2=np.array([[[2,4],[4,5]],[[3,9],[6,7]]])

In [17]:
arr2

array([[[2, 4],
        [4, 5]],

       [[3, 9],
        [6, 7]]])

In [18]:
arr2.ndim

3

In [19]:
arr2.shape

(2, 2, 2)

# Another way of creating np array using arange method

In [20]:
# Hint: work like range function
new_arr=np.arange(16,0,-1)

In [21]:
new_arr

array([16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [22]:
new_arr.ndim

1

In [23]:
len(new_arr)

16

In [24]:
new_arr=new_arr.reshape((2,2,2,2))

In [25]:
new_arr

array([[[[16, 15],
         [14, 13]],

        [[12, 11],
         [10,  9]]],


       [[[ 8,  7],
         [ 6,  5]],

        [[ 4,  3],
         [ 2,  1]]]])

In [26]:
new_arr.ndim

4

# Special Arrays in Numpy
- zeros()
- ones()
- diag()
- identity()

In [27]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.diag((10,2,3))

array([[10,  0,  0],
       [ 0,  2,  0],
       [ 0,  0,  3]])

In [30]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Indexing in Array

In [31]:
new_arr

array([[[[16, 15],
         [14, 13]],

        [[12, 11],
         [10,  9]]],


       [[[ 8,  7],
         [ 6,  5]],

        [[ 4,  3],
         [ 2,  1]]]])

In [32]:
new_arr[1][1][0][0]

4

In [33]:
new_arr[1,1,0,0]

4

In [34]:
new_arr[0][1]

array([[12, 11],
       [10,  9]])

In [35]:
arr= np.array([[2,3,4],[5,6,7],[8,9,10]])

In [36]:
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [37]:
arr[1][1]

6

In [38]:
arr[-1,-1]

10

In [39]:
new_arr[-1][-1]

array([[4, 3],
       [2, 1]])

In [40]:
new_arr[0,-2]     #arr[row,column]

array([[16, 15],
       [14, 13]])

In [41]:
new_arr[-1,-1]

array([[4, 3],
       [2, 1]])

# Array slicing

In [42]:
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [43]:
arr[0:2,:2]

array([[2, 3],
       [5, 6]])

In [44]:
arr[-2::-1,:2]

array([[5, 6],
       [2, 3]])

In [45]:
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [46]:
# second column values

arr[:,-2]

array([3, 6, 9])

In [60]:
arr=np.array([[ 90,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 0]])

In [61]:
arr>6

array([[ True, False, False],
       [False, False,  True],
       [ True,  True, False]])

In [64]:
arr[(arr>6) | (arr%2==0) ]

array([90,  4,  6,  7,  8,  9,  0])

In [53]:
np.log(arr)

array([[0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509]])

In [56]:
np.sin(arr)

array([[ 0.89399666,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849,  0.        ]])

In [57]:
np.sin(90)

0.8939966636005579

In [58]:
np.cos(90)

-0.4480736161291701

In [75]:
np.sqrt(arr)

array([[9.48683298, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 0.        ]])

In [76]:
np.cbrt(arr)

array([[4.48140475, 1.44224957, 1.58740105],
       [1.70997595, 1.81712059, 1.91293118],
       [2.        , 2.08008382, 0.        ]])

In [78]:
arr

array([[90,  3,  4],
       [ 5,  6,  7],
       [ 8,  9,  0]])

In [80]:
np.sum(arr[:,0])

103

In [86]:
np.sum(arr, axis=1)

array([97, 18, 17])

In [81]:
np.mean(arr)

14.666666666666666

In [82]:
np.max(arr)

90

In [83]:
np.min(arr)

0

In [84]:
np.std(arr)

26.758176320519304

# Matrix Product

In [66]:
A= np.random.randint(0,5,(3,4))
B= np.random.randint(0,5,(4,2))

In [67]:
A

array([[0, 4, 0, 2],
       [0, 1, 0, 2],
       [2, 0, 3, 1]])

In [68]:
B

array([[4, 4],
       [2, 3],
       [4, 2],
       [1, 0]])

In [69]:
np.dot(A,B)

array([[10, 12],
       [ 4,  3],
       [21, 14]])

# More Operations on Arrays

In [70]:
A = np.arange(24)

In [71]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [73]:
A=A.reshape((6,4))

In [74]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Shape Manipulation

In [87]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [88]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [89]:
A.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [90]:
np.transpose(A)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [99]:
a = np.random.randint(0,10,(2,2))
b = np.random.randint(0,10,(3,2))
c = np.random.randint(0,5,(3,5))

In [92]:
a

array([[5, 6],
       [9, 0]])

In [93]:
b

array([[9, 3],
       [0, 1],
       [8, 8]])

In [94]:
c

array([[3, 1, 0, 1, 3],
       [0, 1, 4, 0, 0],
       [0, 0, 3, 2, 0]])

In [95]:
np.vstack((a,b))

array([[5, 6],
       [9, 0],
       [9, 3],
       [0, 1],
       [8, 8]])

In [100]:
np.hstack((b,c))

array([[3, 0, 0, 2, 3, 1, 4],
       [0, 9, 4, 1, 4, 4, 2],
       [9, 1, 4, 2, 1, 3, 3]])

# Broadcasting
- First Rule of Numpy : 2 Arrays can performs opertions only when they have same shapes
- broadcasting let two arrays of different shapes to do some operations.
    - A small array will repeat itself, and convert to the same shape as of another array

In [118]:
A = np.random.randint(5, 10, size=(3,3))
B = np.random.randint(0, 5, size=(3,3))
a = np.array([[1,2,3]]) 

In [111]:
A

array([[5, 9, 6],
       [5, 5, 7],
       [9, 8, 6]])

In [112]:
B

array([[3, 4, 1],
       [4, 4, 4],
       [3, 1, 4]])

In [113]:
A+B

array([[ 8, 13,  7],
       [ 9,  9, 11],
       [12,  9, 10]])

In [114]:
A-B

array([[2, 5, 5],
       [1, 1, 3],
       [6, 7, 2]])

In [115]:
A*B

array([[15, 36,  6],
       [20, 20, 28],
       [27,  8, 24]])

In [117]:
A.dot(B)

array([[69, 62, 65],
       [56, 47, 53],
       [77, 74, 65]])

In [119]:
a.T

array([[1],
       [2],
       [3]])

In [124]:
A

array([[8, 8, 5],
       [8, 6, 6],
       [9, 7, 8]])

In [123]:
a

array([[1, 2, 3]])

In [122]:
A +a

array([[ 9, 10,  8],
       [ 9,  8,  9],
       [10,  9, 11]])

In [120]:
A +a.T

array([[ 9,  9,  6],
       [10,  8,  8],
       [12, 10, 11]])

# Vectorization
- performing operations directly on Arrays

In [125]:
p1 = np.array([1,2, 4, 7, -2, 9, 6, 0])
p2 = np.array([5,5, 8, 2, -9, 2, 1, 6])

In [129]:
(np.sum((p2-p1)**2))**0.5

15.0

# Challenges:
sqrt(∑ ( a - b )**2)

# Homework:
Research on add and append function on numpy